title_capitilization: false
name_order: false
title_protect: true
string_journal: false
string_booktitle: false
string_publisher: false
string_year: true
string_month: true
string_type: true
string_address: true
string_location: false
string_institution: true
string_organization: false
string_school: true
string_series: false
bib_keys: false
pages: true
notes: true
required_fields: true
wanted_fields: false
optional_fields: false
